<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "LegalWebTypo3"
 *
 * Auto generated by Extension Builder 2020-08-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Legal Web Typo3',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Legalweb.io',
    'author_email' => 'office@legalweb.io',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.11',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
